### ISSUE TITLE
Removes host files

### ISSUE THREAD

**Issue by jpinon** [drakkar-lig/debootstick#3]
in finalize_fs():
```sh
        rm -rf proc/* sys/* dev/* tmp/* \
            $(find run -type f) /var/cache/* /var/lock
```
This will remove /var/cache/* and /var/lock content on host system.

**Comment by eduble** [comment]
Thanks for reporting. That was a serious issue. I just pushed a fix.
(Some time ago this function was called in the chroot. Then it was adapted to be run from outside, and this issue appeared at this time.)
